### ISSUE TITLE
Moving a show to a diff location

### ISSUE THREAD

**Issue by HaArD2000** [SickGear/SickGear#1268]
BRANCH: develop @ py2.7.13 / COMMIT: 469236d @ 0.22.0

Expectation | Result
------------ | -------------
I am moving two shows, expect to put in the new path, and hit save and have the path to the show be updated. | Instead of making the change I get an error.

Error
GroupResponse instance has no attribute 'hasattr'

**Steps to reproduce:**
*1)* Edit show
*2)* Click Other Tab
*3)* Enter new location
*4)* Click update Show
...

Secret GIST in PM on IRC

<pre>1) HTTPServerRequest(protocol='http', host='192.168.2.100:8081', method='POST', uri='/home/edit-show', version='HTTP/1.1', remote_ip='192.168.2.100')
 2) Traceback (most recent call last):
 3)   File "E:\SickGear\SickGear\lib\tornado_py2\web.py", line 1592, in _execute
 4)     result = yield result
 5)   File "E:\SickGear\SickGear\lib\tornado_py2\gen.py", line 1133, in run
 6)     value = future.result()
 7)   File "E:\SickGear\SickGear\lib\tornado_py2\concurrent.py", line 261, in result
 8)     raise_exc_info(self._exc_info)
 9)   File "E:\SickGear\SickGear\lib\tornado_py2\gen.py", line 307, in wrapper
10)     result = func(*args, **kwargs)
11)   File "E:\SickGear\SickGear\sickbeard\webserve.py", line 823, in get
12)     self.route_method(route, use_404=True)
13)   File "E:\SickGear\SickGear\sickbeard\webserve.py", line 220, in route_method
14)     result = method(**request_kwargs)
15)   File "E:\SickGear\SickGear\sickbeard\webserve.py", line 2581, in edit_show
16)     shortwhitelist = short_group_names(whitelist)
17)   File "E:\SickGear\SickGear\sickbeard\anime.py", line 177, in short_group_names
18)     if None is adba_result or not adba_result.hasattr('datalines'):
19) AttributeError: GroupResponse instance has no attribute 'hasattr'
</pre>

Additional notes:
Current Dir is L:/TV - User
New Dir is I:/TV - Animated

**Comment by JackDandy** [comment]
Will be in next hotfix release

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.25)

Thanks for the report.

**Comment by HaArD2000** [comment]
Still getting the same error on BRANCH: develop @ py2.7.13 / COMMIT: 5e03ba2 @ 0.22.0

**Comment by JackDandy** [comment]
Fixed [here](https://github.com/SickGear/SickGear/releases/tag/release_0.21.26)
