### ISSUE TITLE
ImportError: cannot import name db

### ISSUE THREAD

**Issue by HammyPBB** [SickGear/SickGear#1318]
#### Branch version commit hash: 2da7da3d806533d12c58a04bcf4c44ad194085b3

Expectation | Result
------------ | -------------
Cannot start sickbeard since 10/20/2020

D:\Program Files (x86)\SickGear>"D:\Program Files (x86)\SickGear\sickgear.py"
Traceback (most recent call last):
  File "D:\Program Files (x86)\SickGear\sickgear.py", line 87, in <module>
    import sickbeard
  File "D:\Program Files (x86)\SickGear\sickbeard\__init__.py", line 42, in <module>
    from . import classes, db, helpers, image_cache, indexermapper, logger, metadata, naming, providers, \
  File "D:\Program Files (x86)\SickGear\sickbeard\db.py", line 35, in <module>
    from .helpers import scantree
  File "D:\Program Files (x86)\SickGear\sickbeard\helpers.py", line 42, in <module>
    from . import db, logger, notifiers
  File "D:\Program Files (x86)\SickGear\sickbeard\notifiers\__init__.py", line 24, in <module>
    from . import emby, kodi, plex, xbmc, \
  File "D:\Program Files (x86)\SickGear\sickbeard\notifiers\emailnotify.py", line 29, in <module>
    from .. import db
ImportError: cannot import name db

**Comment by JackDandy** [comment]
This was fixed already.

Try switching to master and then back to develop as it sounds like something has not updated in your files.

**Comment by HammyPBB** [comment]
When I checkout Master and run I get this.

D:\>"D:\Program Files (x86)\SickGear\SickBeard.py"
Starting up SickGear from D:\Program Files (x86)\SickGear\config.ini
Your database version (20014) has been incremented past what this version of SickGear supports
If you have used other forks of SG, your database may be unusable due to their modifications

When doing a checkout of develop I get the same error as before. ImportError: cannot import name db

I am using Git Gui and don't know if I am using the correct requests. Do I do Checkout Branch? Should I be checking out Local branch, Tracking Branch? Tag?

**Comment by HammyPBB** [comment]
Tried checkout of Tracking branch origin\develop and got a bit more output when running but get the ImportError: cannot import name db error still

D:\>"D:\Program Files (x86)\SickGear\sickgear.py"
Starting up SickGear from D:\Program Files (x86)\SickGear\config.ini
No handlers could be found for logger "sickbeard"
11:54:40 INFO TORNADO :: Starting SickGear on http://0.0.0.0:8081/
11:54:40 INFO MAIN :: Database schema is up-to-date, no upgrade required
11:54:40 INFO MAIN :: Checking database structure...
11:54:40 INFO MAIN :: Checking database structure...
11:54:41 INFO MAIN :: No orphan episodes, check passed
11:54:41 INFO MAIN :: No UNAIRED episodes, check passed
11:54:41 INFO MAIN :: Loading initial show list
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  258541,  Chicago Fire
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  295640,  Chicago Med
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  269641,  Chicago P.D.
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  78957,   Deadliest Catch
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  208111,  Gold Rush
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  79485,   How It's Made
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  263365,  Marvel's Agents of S.H.I.E.L.D.
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  259203,  Mountain Men
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  250793,  Ridiculousness
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  161511,  Shameless (US)
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  78901,   Supernatural
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  183231,  Swamp People
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  276515,  The Curse of Oak Island
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  97731,   Tosh.0
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  264234,  Wentworth
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  75692,   Law & Order: Special Victims Unit
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  277928,  Bosch
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  296762,  Westworld
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  314087,  The Grand Tour (2016)
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  73319,   Rick Mercer Report
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  297539,  Treasure Quest: Snake Island
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  280619,  The Expanse
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  326692,  Cooper's Treasure
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  322873,  Mind Field
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  328724,  Young Sheldon
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  237641,  The Fifth Estate
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  336738,  Finding Escobar's Millions
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  301450,  Combat Dealers
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  73762,   Grey's Anatomy
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  295760,  DC's Legends of Tomorrow
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  339227,  Gold Rush: White Water
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  307494,  Jade Fever
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  379221,  Gold Rush: Parker's Trail
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  279121,  The Flash (2014)
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  329175,  Live PD: Police Patrol
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  346762,  Live PD Presents: Women on Patrol
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  80117,   The Real Housewives of Orange County
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  336184,  The Real Housewives of Hungary
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  350050,  Live PD Presents: PD Cam
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  71424,   Dr. Phil
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  361071,  Live Rescue
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  361753,  The Mandalorian
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  357756,  Undone
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  367147,  Marvel's What If...?
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  315976,  Aussie Gold Hunters
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  360432,  Gold Rush: Dave Turin's Lost Mine
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  370271,  River of No Return
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  364088,  FBI: Most Wanted
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  84912,   Parks and Recreation
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  75897,   South Park
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  82696,   Sons of Anarchy
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  280316,  Expedition Unknown
11:54:41 INFO MAIN :: Loaded.. TheTVDB,  272644,  12 Monkeys
11:54:41 INFO LOAD-MAPPINGS :: Start loading TV info mappings...
11:54:41 ERROR CHECKVERSION :: Failed: git symbolic-ref -q HEAD returned:
11:54:42 ERROR CHECKVERSION :: Failed: git symbolic-ref -q HEAD returned:
11:54:42 INFO CHECKVERSION :: New update found for SickGear, starting auto-updater...
11:54:42 ERROR CHECKVERSION :: Failed: git symbolic-ref -q HEAD returned:
11:54:42 INFO LOAD-MAPPINGS :: TV info mappings loaded
11:54:42 ERROR CHECKVERSION :: Failed: git symbolic-ref -q HEAD returned:
11:54:42 INFO POSTPROCESSER :: Processing... Live.Rescue.S03E18.720p.HDTV.x264-CRiMSON[eztv.io].mkv
11:54:42 ERROR CHECKVERSION :: Failed: git symbolic-ref -q HEAD returned:
11:54:42 INFO POSTPROCESSER :: Analyzing name u'Live.Rescue.S03E18.720p.HDTV.x264-CRiMSON[eztv.io]'
11:54:42 WARNING POSTPROCESSER :: Did not use file D:\Download\Live.Rescue.S03E18.720p.HDTV.x264-CRiMSON[eztv.io].mkv
11:54:42 WARNING POSTPROCESSER :: Failed! Did not process any files.
11:54:43 INFO MAIN :: Updating timezone info with new one: zoneinfo-2020d.tar.gz
11:54:43 INFO CHECKVERSION :: Update was successful!
11:54:43 INFO EVENT-QUEUE :: Exiting threads
11:54:43 INFO EVENT-QUEUE :: Thread RECENTSEARCHER has exit
11:54:43 INFO EVENT-QUEUE :: Thread BACKLOG has exit
11:54:43 INFO EVENT-QUEUE :: Thread SHOWUPDATER has exit
11:54:44 INFO FETCH-XEMDATA :: Fetching show ids with xem scene mappings for origin TheTVDB
11:54:44 INFO EVENT-QUEUE :: Thread CHECKVERSION has exit
11:54:44 INFO EVENT-QUEUE :: Thread SHOWQUEUE has exit
11:54:44 INFO EVENT-QUEUE :: Thread SEARCHQUEUE has exit
11:54:44 INFO EVENT-QUEUE :: Thread FINDPROPERS has exit
11:54:44 INFO EVENT-QUEUE :: Thread POSTPROCESSER has exit
11:54:44 INFO EVENT-QUEUE :: Thread FINDSUBTITLES has exit
11:54:44 INFO EVENT-QUEUE :: Thread EMBYWATCHEDSTATE has exit
11:54:44 INFO EVENT-QUEUE :: Thread PLEXWATCHEDSTATE has exit
11:54:44 INFO EVENT-QUEUE :: Thread WATCHEDSTATEQUEUE has exit
11:54:44 INFO EVENT-QUEUE :: Thread EVENT-QUEUE is exiting
11:54:44 INFO EVENT-QUEUE :: Saving all shows to the database
11:54:44 INFO FETCH-XEMDATA :: Finished fetching show ids with 1093 xem scene mappings for origin TheTVDB
11:54:44 INFO EVENT-QUEUE :: Saving config file to disk
11:54:44 INFO EVENT-QUEUE :: Shutting down Tornado
11:54:44 INFO EVENT-QUEUE :: Restarting SickGear with ['D:\\Python27\\python.exe', 'D:\\Program Files (x86)\\SickGear\\sickgear.py', '--nolaunch']
Traceback (most recent call last):
  File "D:\Program Files (x86)\SickGear\sickgear.py", line 87, in <module>
    import sickbeard
  File "D:\Program Files (x86)\SickGear\sickbeard\__init__.py", line 42, in <module>
    from . import classes, db, helpers, image_cache, indexermapper, logger, metadata, naming, providers, \
  File "D:\Program Files (x86)\SickGear\sickbeard\db.py", line 35, in <module>
    from .helpers import scantree
  File "D:\Program Files (x86)\SickGear\sickbeard\helpers.py", line 42, in <module>
    from . import db, logger, notifiers
  File "D:\Program Files (x86)\SickGear\sickbeard\notifiers\__init__.py", line 24, in <module>
    from . import emby, kodi, plex, xbmc, \
  File "D:\Program Files (x86)\SickGear\sickbeard\notifiers\emailnotify.py", line 29, in <module>
    from .. import db
ImportError: cannot import name db

**Comment by JackDandy** [comment]
```
File "D:\Program Files (x86)\SickGear\sickbeard\db.py", line 35, in
from .helpers import scantree
```

That line was removed 3 days ago, your system has not pulled the fix. You need to use your git stuff to pull all files.

**Comment by HammyPBB** [comment]
Thank you so much for all your hard work on this project!!! That fixed me up and I have it for future reference.
