### ISSUE TITLE
Failed to unpack json data: ...  error 2 : No such file or directory

### ISSUE THREAD

**Issue by 0x646e78** [SickGear/SickGear#1334]
#### Branch version commit hash: 

`BRANCH: master @ py2.7.16 / COMMIT: e58fbd8 @ 0.23.5`

Expectation | Result
------------ | -------------
No errors | Errors on alts path.

I have had this recurring issue for the last little while, perhaps 2-3 weeks now, have updated as new releases have come through and persists.

```
2020-12-11 03:50:07 SHOWUPDATER :: Failed to unpack json data: /opt/SickGear/data/cache/alts/tmp/alt.rar with error: error 2 : No such file or directory
2020-12-10 03:50:00 SHOWUPDATER :: Failed to unpack json data: /opt/SickGear/data/cache/alts/tmp/alt.rar with error: error 2 : No such file or directory
2020-12-09 03:49:43 SHOWUPDATER :: Failed to unpack json data: /opt/SickGear/data/cache/alts/tmp/alt.rar with error: error 2 : No such file or directory
```

```
$ sudo ls -al /opt/SickGear/data/cache/
total 48
drwx------  8 pi pi  4096 Dec 11 03:50 .
drwx------  4 pi pi  4096 Dec 11 20:55 ..
drwx------  2 pi pi  4096 Dec 11 21:01 cheetah
drwx------  4 pi pi 20480 Feb  3  2020 images
drwxr-xr-x  2 pi pi  4096 Dec 11 03:50 imdb-pie
drwx------  2 pi pi  4096 Dec  4  2019 indexers
drwx------ 18 pi pi  4096 Dec 11 03:57 sessions
drwx------  2 pi pi  4096 Oct 22 14:15 zoneinfo
```

```
pi       19723 18.2 28.7 522248 287712 ?       Ssl  Dec08 888:52 /opt/SickGear/.pyenv/versions/2.7.16/bin/python2 /opt/SickGear/app/sickgear.py --systemd --datadir=/opt/SickGear/data --port=8081
```

*Additional notes:*

I'm not sure if any config settings would affect this. I didn't see anything else in the logs that would indicate any further info. I think there might be a matching issue in `scene_exceptions.py` as I think from looking at that there's a matching issue where `if fetch_data:` is not being matched, causing the path to not be created. But, I'm not sure, I've only just pulled this codebase down and starting to familiarise myself.

**Comment by JackDandy** [comment]
OS?

**Comment by 0x646e78** [comment]
Sorry @JackDandy I should have included that already.

Raspbian.

```
root@bmo:~# cat /etc/debian_version 
9.13
root@bmo:~# uname -a
Linux raspberry 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux
```

**Comment by JackDandy** [comment]
are you able to dl `https://github.com/SickGear/sickgear.altdata/raw/master/alt.rar` ?

**Comment by JackDandy** [comment]
are you able to ...
1) download `https://github.com/SickGear/sickgear.altdata/raw/master/alt.rar` ? 
2) run `unrar` from a cmd shell ?

**Comment by 0x646e78** [comment]
Ahhh, right! Thanks! 

I found that I had unrar from apt, which as the faq does suggest does not work. I hadn't looked into that enough as I'd gone looking for a folder creation issue.

arm downloads from rarlab don't seem to be available, but there is an alternative from apt named `unar` which handles the windows rars and extracted alt.rar fine. I symlinked to that and the unpack box became happy.

```
sudo ln -s /usr/bin/unar /usr/bin/unrar
```

**Comment by JackDandy** [comment]
Thanks for that useful feedback, it has been added to the FAQ and that log message will be changed to steer people in the right direction. It is factually correct, but not having unrar was not considered as the precursor to why the file doesn't exist.

**Comment by JackDandy** [comment]
@0x646e78 did you miss a msg in your log `Failed to unpack archive...` just before the one you reported `Failed to unpack json data` ?

**Comment by 0x646e78** [comment]
@JackDandy I 99.9% certain I didn't have that log line. Only the Failed to unpack json data line. I did look around for a while.  The system provided unrar was installed, so maybe that's why? I cleared the logs last night so can't check back. 

I've got failure again this morning, with an extra log line. Obviously the `unar` tool doesn't handle flags the same way as `unrar`. I didn't realise to check the flags last night.

I know the password isn't really secret but obfuscating here anyhow.

```
2020-12-12 03:50:29 ERROR    SHOWUPDATER :: Failed to unpack json data: /opt/SickGear/data/cache/alts/tmp/alt.rar with error: error 2 : No such file or directory
2020-12-12 03:50:29 ERROR    SHOWUPDATER :: Failed to unpack archive: /opt/SickGear/data/cache/alts/tmp/alt.rar with error: Non-fatal error [1]: Unknown option -y.
 1) Unknown option -idq.
 2) Unknown option -p<password>.
```

This works (unpacks to `alt/alt.json`):

```
unar -i -d -q -p <password> alt.rar
```

But this fails:

```
$ unar -idq -p<password> alt.rar 
Unknown option -idq.
Unknown option -p<password>.
```

Annoying huh. 

Looks like there was some initial support work for unar as an alt here but I think to support multiple ALT unrars that'd have to extend out to a list and not sure if that's a good direction, probably better for me to find a suitable alternative unrar for arm/pi: https://github.com/SickGear/SickGear/blob/886585816f7b1177ff7d18375a93fb40f7ab0a5d/lib/rarfile_py2/rarfile.py#L227

I did also find an arm download of 5.5 from rarlab here: https://www.rarlab.com/rar_add.htm and have also built 6 from source but they seem different again:

```
$ ./unrar/unrar help

UNRAR 6.00 freeware      Copyright (c) 1993-2020 Alexander Roshal

Usage:     unrar <command> -<switch 1> -<switch N> <archive> <files...>
               <@listfiles...> <path_to_extract\>

<Commands>
  e             Extract files without archived paths
  l[t[a],b]     List archive contents [technical[all], bare]
  p             Print file to stdout
  t             Test archive files
  v[t[a],b]     Verbosely list archive contents [technical[all],bare]
  x             Extract files with full path

<Switches>
  -             Stop switches scanning
  @[+]          Disable [enable] file lists
  ad[1,2]       Alternate destination path
  ag[format]    Generate archive name using the current date
  ai            Ignore file attributes
  ap<path>      Set path inside archive
  c-            Disable comments show
  cfg-          Disable read configuration
  cl            Convert names to lower case
  cu            Convert names to upper case
  dh            Open shared files
  ep            Exclude paths from names
  ep3           Expand paths to full including the drive letter
  f             Freshen files
  id[c,d,n,p,q] Display or disable messages
  ierr          Send all messages to stderr
  inul          Disable all messages
  kb            Keep broken extracted files
  n<file>       Additionally filter included files
  n@            Read additional filter masks from stdin
  n@<list>      Read additional filter masks from list file
  o[+|-]        Set the overwrite mode
  ol[a]         Process symbolic links as the link [absolute paths]
  or            Rename files automatically
  ow            Save or restore file owner and group
  p[password]   Set password
  p-            Do not query password
  r             Recurse subdirectories
  sc<chr>[obj]  Specify the character set
  sl<size>      Process files with size less than specified
  sm<size>      Process files with size more than specified
  ta[mcao]<d>   Process files modified after <d> YYYYMMDDHHMMSS date
  tb[mcao]<d>   Process files modified before <d> YYYYMMDDHHMMSS date
  tn[mcao]<t>   Process files newer than <t> time
  to[mcao]<t>   Process files older than <t> time
  ts[m,c,a,p]   Save or restore time (modification, creation, access, preserve)
  u             Update files
  v             List all volumes
  ver[n]        File version control
  vp            Pause before each volume
  x<file>       Exclude specified file
  x@            Read file names to exclude from stdin
  x@<list>      Exclude files listed in specified list file
  y             Assume Yes on all queries
```

I'll keep looking for options and keep you posted.

Thanks for your help, and the contnual work on this, really is a great application and the best sick*. Been good looking through the code a bit now so hopefully might be able to PR next time I raise an Issue.

**Comment by JackDandy** [comment]
The existing rarfile library will be replaced with a command wrapper because the new Rarfile library code has made breaking changes.  One breaking change removed its extractall() function, a deal breaking change. The wrapper handles the different args of unar vs unrar. So don't worry about this error for now.

**Comment by 0x646e78** [comment]
Oh cool, so I should just keep `unar` for now with that symlink then @JackDandy ? I _think_ from what you're saying it might be better not to symlink and just keep stock unar so that the new wraper will handle it properly?

**Comment by JackDandy** [comment]
exactly that. however, there are issues here. the unrar you had, that others may have, is failing, and even with the wrapper, that failure would still occur, so he root issue should really be handled in code. And yes, that symlink should be removed, as your tests have proven it no use. the other issue is that the entire file around this very low priority feature is undergoing a test phase of a complete overhaul and so cannot really dip in there at the moment either - unless to make change only in that very specific function logic block.

**Comment by 0x646e78** [comment]
Thanks fo rthe update @JackDandy I think the direction sounds good. After my last update I'd rm'd the symlink and put the `unrar` 6 I'd built from source in it's place, so maybe that took care of it for now also.

**Comment by JackDandy** [comment]
Are you able to rename the `unrar` to `unrar.v6` and reinstate in the `unrar` that failed and still get the original fault that you reported, for a test?

**Comment by 0x646e78** [comment]
Done.

```
$ which unrar
/usr/bin/unrar

$ unrar --version
unrar 0.0.1

$ dpkg -l |grep unrar
ii  unrar-free                           1:0.0.1+cvs20140707-1             armhf        Unarchiver for .rar files
```

I still have `unar` installed also.

This issue is already closed by you,  I understand correctly, what I'm looking for at a point in future is for a change in the error message at some point and possibly unar being handled/fallback?

**Comment by JackDandy** [comment]
> a change in the error message and unar being handled/fallback?

Exactly that.

So you still have the bad unrar -- great. I'll get back to you when a fix is ready for your original issue to test.

**Comment by JackDandy** [comment]
Hiya @0x646e78 I have an update ready for testing, let me know when you're ready.

**Comment by 0x646e78** [comment]
@JackDandy cool, just let me know what you want me to do and I'll test it out.

**Comment by JackDandy** [comment]
@0x646e78 I will need you in IRC.
